id = "remark-lsp"
name = "Remark LSP"
description = "Integrates the remark language server"
version = "0.1.0"
schema_version = 1
authors = ["Ivan Porto Carrero <ivan@flanders.co.nz>"]
repository = "https://github.com/casualjim/remark"

[language_servers.remark-lsp]
name = "Remark LSP"
languages = [
  "Rust",
  "Go",
  "JavaScript",
  "TypeScript",
  "JSX",
  "TSX",
  "Python",
  "JSON",
  "JSONC",
  "CSS",
  "GraphQL",
  "TOML",
  "YAML",
  "Markdown"
]
